apiVersion: v1
kind: Pod
metadata:
  name: filebeat-pod
spec:
  restartPolicy: Never #OnFailure
  containers:
  - name: fb01
    image: {{ filebeat.image.name }}
    resources:
      requests:
        memory: {{ filebeat.resources.requests.memory }}
      limits:
        memory: {{ filebeat.resources.limits.memory }}
    volumeMounts:
    - mountPath: /usr/share/filebeat/filebeat.yml
      name: filebeat-conf
  volumes:
  - name: filebeat-conf
    hostPath:
      path: /opt/filebeat/filebeat.yml
