apiVersion: v1
kind: Pod
metadata:
  labels:
    app: filebeat-pod
  name: filebeat-pod
spec:
  restartPolicy: Always
  containers:
  - name: fb01
    image: {{ filebeat.image.name }}
    resources:
      requests:
        memory: {{ filebeat.resources.requests.memory }}
      limits:
        memory: {{ filebeat.resources.limits.memory }}
    securityContext:
      allowPrivilegeEscalation: true
      privileged: false
      capabilities:
        add: []
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - mountPath: /usr/share/filebeat/data
      name: filebeat-data
    - mountPath: /usr/share/filebeat/filebeat.yml
      name: filebeat-conf
      readOnly: true
    {% for volMount in filebeat.podcfg.volumeMounts %}
    - mountPath: {{ volMount.mountPath }}
      name: {{ volMount.name }}
      readOnly: true
    {% endfor %}
  volumes:
  - name: filebeat-data
    persistentVolumeClaim:
      claimName: filebeat-data
  - name: filebeat-conf
    hostPath:
      path: /opt/filebeat/filebeat.yml
  {% for vol in filebeat.podcfg.volumes %}
  - name: {{ vol.name }}
    {{ vol.type }}:
      {{ vol.opt }}
  {% endfor %}
